sudo: required
services:
  - docker

before_install:
  - docker build -t jireymendez/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jireymendez/react-test npm test

after_success:
  - docker build -t jireymendez/multi-client ./client
  - docker build -t jireymendez/multi-server ./server
  - docker build -t jireymendez/multi-worker ./worker
  - docker build -t jireymendez/multi-nginx ./nginx
# Log into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push images to Docker hub
  - docker push jireymendez/multi-client 
  - docker push jireymendez/multi-server 
  - docker push jireymendez/multi-worker 
  - docker push jireymendez/multi-nginx 

deploy:
  provider: azure_web_apps
  #username: azure_deployment_user       # If AZURE_WA_USERNAME isn't set
  #password: azure_deployment_password   # If AZURE_WA_PASSWORD isn't set
  #site: azure_deployment_sitename       # If AZURE_WA_SITE isn't set
  #slot: azure_deployment_slotname       # (optional) If AZURE_WA_SLOT isn't set
  on:
    branch: master